Update telling-git-about-your-signing-key.md Changing from `$(tty)` to `$TTY` as suggested [in here](https://unix.stackexchange.com/a/608921) by the maintainer of [Powerlevel10k](https://github.com/romkatv/powerlevel10k) fixed the issue for the user who posted the question, which was the same as mine.
Before I made the change I was able to generate my `GPG` key, but I was getting the following error:

```bash
$ git commit -S -m "First signed commit"
error: gpg failed to sign the data
fatal: failed to write commit object
```

And this was another sign of the problem:

```bash
$ echo $GPG_TTY
not a tty
```

Adding `export GPG_TTY=$TTY` to my `.zshrc` fixed the issue.