Add RepositoryType to .csproj examples
I was banging my head against the wall for a long time getting this kind of response when pushing (using a nuget.config file)

```
$ dotnet nuget push "releases/<packages>.nupkg" --source "github" --api-key <PAT_TOKEN>
Pushing <package> to 'https://nuget.pkg.github.com/<owner>'...
  PUT https://nuget.pkg.github.com/<owner>/
warn : No destination repository detected. Ensure the source project has a 'RepositoryUrl' property defined. If you're using a nuspec file, ensure that it has a repository element with the required 'type' and 'url' attributes.
  BadRequest https://nuget.pkg.github.com/<owner>/ 102ms
error: Response status code does not indicate success: 400 (Bad Request).
```

Adding the `<RepositoryType>git</RepositoryType>` solved the problem.