Clean up dependencies (#19633)
* Just use core Node assert module instead of the browserify one

* Get peerDeps for styled-components into lockfile

* Remove 2 unused csv-parse(r) devDeps that probably got installed during interviews LOL whoops

* Remove unused jest-silent-reporter devDep

* Remove unused mime devDep

* Remove unused postcss devDep

* Remove unused process devDep

* Update sass devDep to latest

* Reintroduce postcss devDep

Error: Cannot find module 'postcss'
Require stack:
- /home/runner/work/docs-internal/docs-internal/node_modules/cssnano-simple/src/index.js
- /home/runner/work/docs-internal/docs-internal/node_modules/next/dist/build/webpack/plugins/font-stylesheet-gathering-plugin.js
- /home/runner/work/docs-internal/docs-internal/node_modules/next/dist/build/webpack-config.js
- /home/runner/work/docs-internal/docs-internal/node_modules/next/dist/build/index.js
- /home/runner/work/docs-internal/docs-internal/node_modules/next/dist/cli/next-build.js
- /home/runner/work/docs-internal/docs-internal/node_modules/next/dist/bin/next