Fix the frontmatter (#28799)
I noticed this when comparing `diff content/billing/index.md translations/pt-BR/content/billing/index.md`

In https://github.com/github/docs-internal/runs/7098669524?check_suite_focus=true we get a weird error:
```
Run crowdin upload sources --delete-obsolete --no-progress --no-colors --verbose --debug '--branch=main' '--config=crowdin.yml'
✔️  Fetching project info
⏭  Branch 'main' already exists in the project
✔️  File 'main/content/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/viewing-and-re-running-checks-in-github-desktop.md'
✔️  File 'main/content/admin/identity-and-access-management/using-saml-for-enterprise-iam/configuring-user-provisioning-for-your-enterprise.md'
✔️  File 'main/content/admin/configuration/configuring-github-connect/about-github-connect.md'
✔️  File 'main/content/repositories/creating-and-managing-repositories/renaming-a-repository.md'
✔️  File 'main/content/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/viewing-contributions-on-your-profile.md'
java.lang.RuntimeException: File 'main/content/billing/index.md'
	at com.crowdin.cli.commands.actions.UploadSourcesAction.lambda$null$8(UploadSourcesAction.java:227)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Wrong parameters: 
<key: storageId, code: fileInvalid, message: Front matter file does not have YAML part.>
	at com.crowdin.cli.client.CrowdinClientCore.executeRequest(CrowdinClientCore.java:120)
	at com.crowdin.cli.client.CrowdinClientCore.executeRequestWithPossibleRetry(CrowdinClientCore.java:88)
	at com.crowdin.cli.client.CrowdinProjectClient.updateSource(CrowdinProjectClient.java:172)
	at com.crowdin.cli.commands.actions.UploadSourcesAction.lambda$null$8(UploadSourcesAction.java:211)
	... 5 more
```
Might solve the problem.