LayoutConverter.java:37
com.google.gson.JsonSyntaxException: Failed to load
	at net.kdt.pojavlaunch.customcontrols.LayoutConverter.loadAndConvertIfNecessary(LayoutConverter.java:37)
	at net.kdt.pojavlaunch.customcontrols.ControlLayout.loadLayout(ControlLayout.java:41)
	at net.kdt.pojavlaunch.CustomControlsActivity.loadControl(CustomControlsActivity.java:228)
	at net.kdt.pojavlaunch.CustomControlsActivity.access$100(CustomControlsActivity.java:21)
	at net.kdt.pojavlaunch.CustomControlsActivity$3.onFileSelected(CustomControlsActivity.java:200)
	at com.kdt.pickafile.FileListView.listFileAt(FileListView.java:143)
	at com.kdt.pickafile.FileListView$1.onItemClick(FileListView.java:74)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1187)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3159)
	at android.widget.AbsListView$3.run(AbsListView.java:4113)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
Caused by: org.json.JSONException: End of input at character 0 of 
	at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
	at org.json.JSONTokener.nextValue(JSONTokener.java:97)
	at org.json.JSONObject.<init>(JSONObject.java:159)
	at org.json.JSONObject.<init>(JSONObject.java:176)
	at net.kdt.pojavlaunch.customcontrols.LayoutConverter.loadAndConvertIfNecessary(LayoutConverter.java:21)
	... 17 more